version: '3.5'
services:
  db:
    container_name: db
    image: mysql:5.7
    # volumes:
    #   # - db:/var/lib/mysql/data
    #   - /opt/var/lib/mysql:/var/lib/mysql
    #   - /opt/var/log/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: test
    ports:
      - "127.0.0.1:3306:3306"
    # deploy:
    #   mode: replicated
    #   replicas: 1
      # endpoint_mode: dnsrr
  